# -*- coding: utf-8 -*-
"""Predicting Flower Types

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11kaVFGqceA2PVu8bKoaz6oN-CCUEEY1F
"""

import pandas as pd

path = "/content/drive/MyDrive/Dataset/Iris.csv"
df = pd.read_csv(path)
df.head(200)



import seaborn as sns
sns.set(style="white", color_codes =True)

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
# %matplotlib inline

df["Species"].value_counts()

sns.FacetGrid(df, hue = "Species", height = 6).map(plt.scatter, "PetalLengthCm", "SepalWidthCm").add_legend()

mapping = {"Iris-setosa": 0, "Iris-versicolor": 1, "Iris-virginica": 2}
df["Species"] = df["Species"].map(mapping)

df.head(200)

x = df[["SepalLengthCm", "SepalWidthCm", "PetalLengthCm", "PetalWidthCm"]].values
y = df[["Species"]].values

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(x,y)

model.score(x, y)

expected = y
predicted = model.predict(x)
predicted

from sklearn import metrics

print(metrics.classification_report(expected, predicted))

print(metrics.confusion_matrix(expected, predicted))